name: CD - APIM-Mediation-Policies

on:
  push:
    branches:
      - uat
    paths:
      - apim/policies/mediation/**/release.json
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_apim_policies:
    name: Deploy APIM Policies
    uses: wso2-cicd/wso2-workflows/.github/workflows/cd-apim-mediation-policies.yml@main
    with:
      sourceBranch: uat
      destinationBranch: prod
      sourceEnv: uat
      destinationEnv: prod
      apiCtlEnv: uat
    secrets:
      ghBotPat: ${{ secrets.WSO2_GIT_BOT_PAT }}
      ghBotUsername: ${{ secrets.WSO2_GIT_BOT_USERNAME }}
      ghBotEmail: ${{ secrets.WSO2_GIT_BOT_EMAIL }}
      apimAdminUsername: ${{ secrets.WSO2_APIM_UAT_ADMIN_USERNAME }}
      apimAdminPassword: ${{ secrets.WSO2_APIM_UAT_ADMIN_PASSWORD }}